### ISSUE TITLE
Wikis aren't imported from html files when run on 64-bit linux

### ISSUE THREAD

**Issue by inmysocks** [mklauber/TiddlyServer#2]
I am using 64-bit Linux Mint 18

Importing a wiki from a folder works as expected, but importing an html file creates an empty wiki.

Everything else seems to be working correctly.

**Comment by inmysocks** [comment]
Or it is working. Ignore this, it looks like I just made a mistake somewhere.

**Comment by mklauber** [comment]
I thought I had something working, but I saw some issues during development too.  If you get any repeatable failures, let me know.
